export const POST_TRACKING_DATA_REQUEST = "POST_TRACKING_DATA_REQUEST";
export const POST_TRACKING_DATA_SUCCESS = "POST_TRACKING_DATA_SUCCESS";
export const POST_TRACKING_DATA_FAILURE = "POST_TRACKING_DATA_FAILURE";

export const GET_TRACKING_DATA_REQUEST = "GET_TRACKING_DATA_REQUEST";
export const GET_TRACKING_DATA_SUCCESS = "GET_TRACKING_DATA_SUCCESS";
export const GET_TRACKING_DATA_FAILURE = "GET_TRACKING_DATA_FAILURE";

